#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import crypto from 'node:crypto';
const root=process.cwd(),regPath=path.join(root,'data/release/frozen_output_registry.json'),copyPath=path.join(root,'data/content/generated_route_copy.json'),registryPath=path.join(root,'data/content/page_registry.json'),scopePath=path.join(root,'data/release/active_mutation_scope.json'),cacheDir=path.join(root,'data/release/frozen_accepted_outputs');
const sortObj=o=>Array.isArray(o)?o.map(sortObj):(o&&typeof o==='object'?Object.fromEntries(Object.keys(o).sort().map(k=>[k,sortObj(o[k])])):o),stable=o=>Buffer.from(JSON.stringify(sortObj(o))+'\n'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),load=(p,f)=>fs.existsSync(p)?JSON.parse(fs.readFileSync(p,'utf8')):f,scope=()=>new Set((load(scopePath,{routes:[]}).routes||[]));
function status(){const reg=load(regPath,{records:{}}),doc=load(copyPath,{routes:{}}),s=scope();let drift=0,missing=0;for(const [route,r] of Object.entries(reg.records||{})){if(!(route in doc.routes)){missing++;continue;}if(!s.has(route)&&hash(stable(doc.routes[route]))!==r.sha256)drift++;}console.log(JSON.stringify({command:'status',frozen:Object.keys(reg.records||{}).length,active_mutation_routes:s.size,unscoped_drift:drift,missing_payloads:missing},null,2));if(drift||missing)process.exit(1);}
function restore(){const reg=load(regPath,{records:{}}),doc=load(copyPath,{routes:{}}),s=scope();let restored=0,thawed=0,missing=0;for(const [route,r] of Object.entries(reg.records||{})){if(s.has(route)){thawed++;continue;}const b=path.join(root,r.blob||'');if(!fs.existsSync(b)){missing++;continue;}const frozen=JSON.parse(zlib.gunzipSync(fs.readFileSync(b)).toString('utf8'));if(!(route in doc.routes)||hash(stable(doc.routes[route]))!==r.sha256){doc.routes[route]=frozen;restored++;}}fs.writeFileSync(copyPath,JSON.stringify(doc,null,2)+'\n');console.log(JSON.stringify({command:'restore',restored,transactionally_thawed:thawed,missing_cache:missing},null,2));if(missing)process.exit(1);}
function prepare(){const routes=[];const plan=load(path.join(root,'data/intelligence/page_action_decisions.json'),{});for(const x of plan.decisions||plan.actions||[])if(x.route&&(x.action==='repair_existing'||x.recommendedAction==='repair_existing'))routes.push(x.route);fs.writeFileSync(scopePath,JSON.stringify({schema_version:'1.0',generated_at:new Date().toISOString(),source:'page_action_decisions',routes:[...new Set(routes)].sort()},null,2)+'\n');console.log(JSON.stringify({command:'prepare-scope',routes:new Set(routes).size},null,2));}
function freeze(){const old=load(regPath,{records:{}}),doc=load(copyPath,{routes:{}}),pages=load(registryPath,{pages:[]}).pages||[],s=scope(),unscoped=[];for(const [route,r] of Object.entries(old.records||{})){if(route in doc.routes&&hash(stable(doc.routes[route]))!==r.sha256&&!s.has(route))unscoped.push(route);}if(unscoped.length){console.error(JSON.stringify({error:'UNSCOPED_FROZEN_PAYLOAD_DRIFT',count:unscoped.length,sample:unscoped.slice(0,20)},null,2));process.exit(1);}fs.mkdirSync(cacheDir,{recursive:true});const records={};for(const p of pages){if(p.status!=='published_by_contract'||!doc.routes?.[p.path])continue;const raw=stable(doc.routes[p.path]),h=hash(raw),blob=`data/release/frozen_accepted_outputs/${h}.json.gz`,abs=path.join(root,blob);if(!fs.existsSync(abs))fs.writeFileSync(abs,zlib.gzipSync(raw,{level:9,mtime:0}));records[p.path]={sha256:h,blob};}const keep=new Set(Object.values(records).map(r=>path.basename(r.blob)));for(const n of fs.readdirSync(cacheDir))if(n.endsWith('.json.gz')&&!keep.has(n))fs.rmSync(path.join(cacheDir,n),{force:true});fs.writeFileSync(regPath,JSON.stringify({schema_version:'1.1',policy:'accepted_source_payload_freeze',source_file:'data/content/generated_route_copy.json',accepted_status:'published_by_contract',mutation_scope:'data/release/active_mutation_scope.json',records},null,2)+'\n');console.log(JSON.stringify({command:'freeze',frozen:Object.keys(records).length,accepted_mutation_routes:s.size,unscoped_drift:0},null,2));}
function clear(){fs.rmSync(scopePath,{force:true});console.log(JSON.stringify({command:'clear-scope',cleared:true},null,2));}
const cmd=process.argv[2]||'status';const fn={status,restore,freeze,'prepare-scope':prepare,'clear-scope':clear}[cmd];if(!fn)throw new Error(`unknown ${cmd}`);fn();
